### ISSUE TITLE
[Req] Sort friends by in-game, on line, offline

### ISSUE THREAD

**Issue by LossyDragon** [Longi94/Vapulla#9]
### Requested feature

It would be a great feature to have your friends list have an option to sort by Recent Chats, online, offline, and in game. Similar to how steam does it on desktop, but with the addiction of recent chats for mobile use. 

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version:
  - Platform:

**Comment by LossyDragon** [comment]
Should note that it already sorts recent chats on the top of the list, but the lack of a divider for simple categories makes it hard to see at a first glance.

**Comment by Longi94** [comment]
Steam mobile does have a recent chats section, but it removes users from that category after a while. Most if not all chat applications keep the most recent chat on top forever. Which one do you have in mind.

I don't like the idea of removing chats from the recents category, but at the same time I feel like a recents category kind of loses it's purpose once it gets filled up with a lot of chats.

As mentioned in #8 adding a timestamp to the list would make the ordering clear imo.

**Comment by LossyDragon** [comment]
Couldn't the application take care of recent chat sorting? Then after a couple of days they would fall off until the next message is sent.

**Comment by LossyDragon** [comment]
Unless steam's version has a reasonable time frame before it drops it off on steam's end

**Comment by Longi94** [comment]
Sorting is done by the application, steam doesnt sort chats or mark them as recent.
